apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: springk8s-backend
  name: springk8s-backend
  namespace: springk8s
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    k8s-app: springk8s-backend