apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springk8s-pvc
  namespace: springk8s
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi